# Generated by Django 3.2.9 on 2021-12-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='year_published',
            field=models.DateField(default=None),
        ),
    ]
