# Generated by Django 3.2.9 on 2021-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_songinfo_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='album_cover_url',
            field=models.CharField(max_length=500),
        ),
    ]
